name: tests

on: [push, pull_request]

jobs:
  spellcheck:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2

    - name: Install codespell
      run: pip install codespell

    - name: Spellcheck
      run: |
        codespell --ignore-words-list="crate"
        echo "Spellcheck complete"
